---

- name: Configure the web server
  hosts: guests
  user: root
  vars:
    package_dir: /srv/http/packages
  tasks:

  - name: Install Apache
    action: yum pkg=httpd state=installed

  - name: Configure yum package location
    action: template src=../templates/etc/httpd/conf.d/packages.conf dest=/etc/httpd/conf.d/packages.conf

  - name: Start and enable Apache
    action: service name=httpd state=started enabled=yes
