---

- name: Configure the web server
  hosts: guests
  user: root
  vars:
    package_dir: /srv/http/packages
    centos_image: /srv/http/packages/CentOS-6.4-x86_64-bin-DVD1.iso

  handlers:
  - name: Restart Apache
    action: service name=httpd state=restarted

  tasks:

  - name: Install Apache
    action: yum pkg=httpd state=installed

  - name: Configure yum package location
    action: template src=../templates/etc/httpd/conf.d/packages.conf dest=/etc/httpd/conf.d/packages.conf
    notify:
    - Restart Apache

  - name: Start and enable Apache
    action: service name=httpd state=started enabled=yes

  - name: Create tree location
    action: file dest=${packages_path}/tree state=directory
  - name: Copy CentOS ISO image
    local_action: command rsync -a --inplace --rsh='ssh -o StrictHostKeyChecking=no' ${packages_path}/CentOS-6.4-x86_64-bin-DVD1.iso root@${inventory_hostname}:${packages_path}/CentOS-6.4-x86_64-bin-DVD1.iso
  - name: Loopback mount the image
    action: mount name=${packages_path}/tree src=${centos_image} opts=ro,loop fstype=iso9660 state=mounted

  - name: Create CentOS repository location
    action: file dest=${packages_path}/centos state=directory
  - name: Copy RPMS
    action: copy src=${packages_path}/centos/$item dest=${packages_path}/centos/$item
    with_items:
    - ansible-1.0-1.el6.noarch.rpm
    - PyYAML-3.10-3.el6.x86_64.rpm
    - libyaml-0.1.3-1.el6.x86_64.rpm
  - name: Create repository
    action: command createrepo ${packages_path}/centos/
