---

- name: Configure the web server
  hosts: guests
  user: root
  vars:
    packages_path: /srv/http/packages
    centos_image: /srv/http/packages/CentOS-6.4-i386-minimal.iso

  handlers:
  - name: Restart Apache
    action: service name=httpd state=restarted

  tasks:

  - name: Install Apache
    action: yum pkg=httpd state=installed

  - name: Configure yum package location
    action: template src=../templates/etc/httpd/conf.d/packages.conf dest=/etc/httpd/conf.d/packages.conf
    notify:
    - Restart Apache

  - name: Start and enable Apache
    action: service name=httpd state=started enabled=yes

  - name: Create OS directory
    action: file dest=${packages_path}/minimal state=directory

  - name: Copy CentOS minimal ISO image
#    action: copy src=${centos_image} dest=${centos_image}
    local_action: command rsync -a --inplace --rsh='ssh -o StrictHostKeyChecking=no' ${centos_image} root@${inventory_hostname}:${centos_image}

  - name: Loopback mount the image
    action: mount name=${packages_path}/minimal src=${centos_image} opts=ro,loop fstype=iso9660 state=mounted

  - name: Create Workshop workshop directory
    action: file dest=${packages_path}/workshop state=directory

  - name: Copy Workshop RPMS
    action: copy src=$item dest=$item
    with_fileglob: ${packages_path}/workshop/*.rpm
#    with_items:
#    - PyYAML-3.10-3.el6.x86_64.rpm
#    - ansible-1.0-1.el6.noarch.rpm
#    - apr-1.3.9-5.el6_2.i686.rpm
#    - apr-util-1.3.9-3.el6_0.1.i686.rpm
#    - apr-util-ldap-1.3.9-3.el6_0.1.i686.rpm
#    - createrepo-0.9.9-17.el6.noarch.rpm
#    - deltarpm-3.5-0.5.20090913git.el6.i686.rpm
#    - httpd-2.2.15-26.el6.centos.i686.rpm
#    - httpd-tools-2.2.15-26.el6.centos.i686.rpm
#    - libxml2-python-2.7.6-8.el6_3.4.i686.rpm
#    - libyaml-0.1.3-1.el6.x86_64.rpm
#    - mailcap-2.1.31-2.el6.noarch.rpm
#    - python-deltarpm-3.5-0.5.20090913git.el6.i686.rpm
#    - python-jinja2-2.2.1-1.el6.x86_64.rpm

  - name: Create repository
    action: command createrepo ${packages_path}/workshop/
